revision = 'f0e8d460d2ad'
down_revision = None
branch_labels = None
depends_on = None

"""Auto-generated migration

Revision ID: f0e8d460d2ad
Revises: None
Create Date: 2025-12-18 01:46:17
"""

from alembic import op
import sqlalchemy as sa


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
